/**
 * The bulk booking import: parsing, preview, commit, undo.
 *
 * The guarantees under test are the ones that stop the two systems disagreeing and stop
 * the ledger drifting: nothing is written before confirmation, an already-booked passport
 * cannot be booked again by any path, a booking and its charge land together or not at
 * all, undoing an import leaves no money owed, and re-uploading a file changes nothing.
 */

import assert from 'node:assert/strict';
import { after, before, beforeEach, describe, it } from 'node:test';

import { ObjectId } from 'mongodb';

import { parseAppointmentDate, parseAppointmentTime, parseBookingFile, UnreadableFileError } from '@/lib/import/parse';
import { DEFAULT_BOOKING_IMPORT_TEMPLATE } from '@/lib/import/mapping';

import { resetData, seedFixtures, startTestDb, stopTestDb, type Fixtures, type TestContext } from './helpers/db';

let ctx: TestContext;
let fx: Fixtures;

before(async () => {
  ctx = await startTestDb();
});

after(async () => {
  await stopTestDb();
});

beforeEach(async () => {
  await resetData(ctx.client);
  fx = await seedFixtures(ctx);
});

const admin = () => ctx.actor.adminActor(fx.adminId);
const asA = () => ctx.actor.agencyActor(fx.userA, fx.agencyA);

function row(passportNumber: string, overrides: Record<string, unknown> = {}) {
  return {
    firstName: 'Test',
    lastName: 'Person',
    passportNumber,
    passportExpiryDate: '2032-09-15',
    dateOfBirth: '1995-07-11',
    nationality: 'EGY',
    gender: 'Female' as const,
    routeId: fx.routeId.toHexString(),
    ...overrides,
  };
}

/** Passports at `added` — where they sit when a booking file comes back. */
async function seedAdded(numbers: string[]): Promise<ObjectId[]> {
  const batch = await ctx.dal.createPassports(asA(), numbers.map((number) => row(number)));
  const ids = batch.rows.map((r) => new ObjectId(r.passportId!));
  await ctx.dal.changePassportStatuses(admin(), ids, 'ready');
  await ctx.dal.markAsAdded(admin(), ids);
  return ids;
}

function csvFile(rows: string[][], filename = 'bookings.csv') {
  const body = rows.map((cells) => cells.map((cell) => `"${cell.replace(/"/g, '""')}"`).join(',')).join('\r\n');
  return { buffer: Buffer.from(body, 'utf8'), filename };
}

const HEADER = ['Passport Number', 'Appointment Date', 'Appointment Time', 'Location', 'Reference'];

describe('reading a booking file', () => {
  it('finds the header even under a title block and blank rows', async () => {
    const file = csvFile([
      ['VISA APPOINTMENTS — WEEK 33', '', '', '', ''],
      ['Generated by the booking system', '', '', '', ''],
      ['', '', '', '', ''],
      HEADER,
      ['A10000001', '27/08/2026', '09:30', 'VFS Cairo', 'REF-1'],
    ]);

    const parsed = await parseBookingFile(file);
    assert.equal(parsed.headerRow, 4);
    assert.equal(parsed.rows.length, 1);
    assert.equal(parsed.rows[0]!.passportNumberNormalized, 'A10000001');
  });

  it('matches columns however they are spelled, in any order', async () => {
    const parsed = await parseBookingFile(
      csvFile([
        ['Ref', 'Passport No.', 'Appt Date', 'Centre'],
        ['REF-9', 'A10000001', '27/08/2026', 'VFS Cairo'],
      ]),
    );

    assert.deepEqual(
      parsed.recognisedColumns.map((column) => column.field).sort(),
      ['appointmentDate', 'location', 'passportNumber', 'reference'],
    );
    assert.equal(parsed.rows[0]!.reference, 'REF-9');
  });

  it('strips stray spaces out of a passport number for matching, keeping the original', async () => {
    const parsed = await parseBookingFile(csvFile([HEADER, [' a1000 0001 ', '27/08/2026', '', '', '']]));

    assert.equal(parsed.rows[0]!.passportNumberNormalized, 'A10000001');
    assert.equal(parsed.rows[0]!.passportNumber, 'a1000 0001');
  });

  it('refuses a file that does not look like a booking file, and says why', async () => {
    const file = csvFile([
      ['Client', 'Amount Paid', 'Notes'],
      ['karam', '3904.00', 'First installment'],
    ]);

    await assert.rejects(
      () => parseBookingFile(file),
      (error: Error) => {
        assert.ok(error instanceof UnreadableFileError);
        assert.match(error.message, /does not look like a booking file/i);
        assert.ok(error.detail.some((line) => /passport number/i.test(line)));
        return true;
      },
    );
  });

  it('refuses a file type it cannot read at all', async () => {
    await assert.rejects(
      () => parseBookingFile({ buffer: Buffer.from('x'), filename: 'bookings.pdf' }),
      (error: Error) => error instanceof UnreadableFileError,
    );
  });

  it('reports an unreadable row instead of guessing at it', async () => {
    const parsed = await parseBookingFile(
      csvFile([
        HEADER,
        ['A10000001', '27/08/2026', '09:30', 'VFS Cairo', 'REF-1'],
        ['A10000002', 'next Tuesday', '', '', ''],
        ['', '27/08/2026', '', '', ''],
      ]),
    );

    assert.equal(parsed.rows.length, 1);
    assert.equal(parsed.rejected.length, 2);
    assert.match(parsed.rejected[0]!.problems[0]!, /could not read "next tuesday" as a date/i);
    assert.match(parsed.rejected[1]!.problems[0]!, /no passport number/i);
  });
});

describe('reading dates without guessing', () => {
  it('reads a slash date day-first, like everything else in this data', () => {
    const { date } = parseAppointmentDate('05/06/2028', 'day-first');
    assert.equal(date?.toISOString().slice(0, 10), '2028-06-05');
  });

  it('takes an ISO date as ISO', () => {
    const { date } = parseAppointmentDate('2028-06-05', 'day-first');
    assert.equal(date?.toISOString().slice(0, 10), '2028-06-05');
  });

  it('rejects a date that contradicts the configured order rather than swapping it', () => {
    const { date, problem } = parseAppointmentDate('08/27/2026', 'day-first');
    assert.equal(date, null);
    assert.match(problem!, /month reads as 27/);
  });

  it('rejects a date that does not exist', () => {
    const { date } = parseAppointmentDate('31/02/2026', 'day-first');
    assert.equal(date, null);
  });

  it('reads the time formats these files use', () => {
    assert.deepEqual(parseAppointmentTime('09:30'), { hours: 9, minutes: 30 });
    assert.deepEqual(parseAppointmentTime('2:30 PM'), { hours: 14, minutes: 30 });
    assert.deepEqual(parseAppointmentTime('1430'), { hours: 14, minutes: 30 });
    assert.equal(parseAppointmentTime('half nine'), null);
  });
});

describe('the preview', () => {
  it('writes nothing at all', async () => {
    const ids = await seedAdded(['A10000001', 'A10000002']);
    const before = await ctx.dal.countByStatus(admin());

    await ctx.dal.previewImport(
      admin(),
      csvFile([HEADER, ['A10000001', '27/08/2026', '09:30', 'VFS Cairo', 'REF-1']]),
    );

    assert.deepEqual(await ctx.dal.countByStatus(admin()), before);
    const bookings = await ctx.collections.bookings();
    assert.equal(await bookings.countDocuments({}), 0);
    assert.equal(ids.length, 2);
  });

  it('separates what will book, what matched nothing, and what is already booked', async () => {
    const ids = await seedAdded(['A10000001', 'A10000002']);
    // Book the first one already.
    await ctx.dal.commitImport(
      admin(),
      csvFile([HEADER, ['A10000001', '20/08/2026', '09:30', 'VFS Cairo', 'REF-0']], 'first.csv'),
    );

    const preview = await ctx.dal.previewImport(
      admin(),
      csvFile(
        [
          HEADER,
          ['A10000001', '27/08/2026', '09:30', 'VFS Cairo', 'REF-1'],
          ['A10000002', '27/08/2026', '10:00', 'VFS Cairo', 'REF-2'],
          ['Z99999999', '27/08/2026', '10:30', 'VFS Cairo', 'REF-3'],
        ],
        'second.csv',
      ),
    );

    assert.equal(preview.counts.will_book, 1);
    assert.equal(preview.counts.already_booked, 1);
    assert.equal(preview.counts.unmatched, 1);
    assert.equal(ids.length, 2);
  });

  it('shows the existing appointment for an already-booked passport', async () => {
    await seedAdded(['A10000001']);
    await ctx.dal.commitImport(
      admin(),
      csvFile([HEADER, ['A10000001', '20/08/2026', '09:30', 'VFS Cairo', 'REF-0']], 'first.csv'),
    );

    const preview = await ctx.dal.previewImport(
      admin(),
      csvFile([HEADER, ['A10000001', '27/08/2026', '11:00', 'VFS Cairo', 'REF-1']], 'second.csv'),
    );

    const row = preview.rows.find((entry) => entry.outcome === 'already_booked');
    assert.ok(row?.existingBooking);
    assert.equal(row.existingBooking.reference, 'REF-0');
    assert.equal(row.existingBooking.appointmentAt.toISOString().slice(0, 10), '2026-08-20');
  });

  it('prices the charges from each passport route, per currency', async () => {
    await seedAdded(['A10000001', 'A10000002']);

    const preview = await ctx.dal.previewImport(
      admin(),
      csvFile([
        HEADER,
        ['A10000001', '27/08/2026', '09:30', 'VFS Cairo', 'REF-1'],
        ['A10000002', '27/08/2026', '10:00', 'VFS Cairo', 'REF-2'],
      ]),
    );

    assert.deepEqual(preview.charges, [{ currency: 'USD', amountMinor: 24_000, count: 2 }]);
  });

  it('says when this exact file has already been imported', async () => {
    await seedAdded(['A10000001']);
    const file = csvFile([HEADER, ['A10000001', '27/08/2026', '09:30', 'VFS Cairo', 'REF-1']]);

    await ctx.dal.commitImport(admin(), file);
    const preview = await ctx.dal.previewImport(admin(), file);

    assert.ok(preview.alreadyImported);
  });

  it('is admin-only', async () => {
    await assert.rejects(
      () => ctx.dal.previewImport(asA(), csvFile([HEADER, ['A10000001', '27/08/2026', '', '', '']])),
      (error: Error) => error.name === 'ForbiddenError',
    );
  });
});

describe('committing', () => {
  it('books, charges, changes the status and records the history together', async () => {
    const [passportId] = await seedAdded(['A10000001']);

    const result = await ctx.dal.commitImport(
      admin(),
      csvFile([HEADER, ['A10000001', '27/08/2026', '09:30', 'VFS Cairo', 'REF-1']]),
    );
    assert.equal(result.booked, 1);

    const passport = await ctx.dal.getPassport(admin(), passportId!);
    assert.equal(passport.status, 'booked');

    const bookings = await ctx.collections.bookings();
    const booking = await bookings.findOne({ passportId });
    assert.ok(booking);
    assert.equal(booking.reference, 'REF-1');
    assert.equal(booking.appointmentAt.toISOString(), '2026-08-27T09:30:00.000Z');
    assert.equal(booking.timezone, DEFAULT_BOOKING_IMPORT_TEMPLATE.timezone);

    const charges = await ctx.collections.charges();
    const charge = await charges.findOne({ passportId });
    assert.ok(charge);
    assert.equal(charge.amountMinor, 12_000);
    assert.equal(charge.currency, 'USD');
    assert.equal(charge.bookingId.toHexString(), booking._id.toHexString());

    const history = await ctx.dal.getPassportHistory(admin(), passportId!);
    assert.equal(history.at(-1)!.status, 'booked');
    assert.equal(history.at(-1)!.via, 'booking_import');
  });

  it('freezes the fee at the moment of booking, so a later price change moves nothing', async () => {
    const [passportId] = await seedAdded(['A10000001']);
    await ctx.dal.commitImport(
      admin(),
      csvFile([HEADER, ['A10000001', '27/08/2026', '09:30', 'VFS Cairo', 'REF-1']]),
    );

    await ctx.dal.updateRoute(admin(), fx.routeId, { feeMinor: 99_900 });

    const charges = await ctx.collections.charges();
    const charge = await charges.findOne({ passportId });
    assert.equal(charge!.amountMinor, 12_000);
  });

  it('leaves already-booked passports alone', async () => {
    await seedAdded(['A10000001', 'A10000002']);
    await ctx.dal.commitImport(
      admin(),
      csvFile([HEADER, ['A10000001', '20/08/2026', '09:30', 'VFS Cairo', 'REF-0']], 'first.csv'),
    );

    const second = await ctx.dal.commitImport(
      admin(),
      csvFile(
        [
          HEADER,
          ['A10000001', '27/08/2026', '09:30', 'VFS Cairo', 'REF-X'],
          ['A10000002', '27/08/2026', '10:00', 'VFS Cairo', 'REF-2'],
        ],
        'second.csv',
      ),
    );

    assert.equal(second.booked, 1);

    // The first passport keeps its original appointment, not the one in the second file.
    const bookings = await ctx.collections.bookings();
    const live = await bookings.find({ undoneAt: null }).toArray();
    assert.equal(live.length, 2);
    assert.equal(live.filter((booking) => booking.reference === 'REF-X').length, 0);
  });

  it('cannot double-book even when the same file is committed twice at once', async () => {
    await seedAdded(['A10000001']);
    const file = csvFile([HEADER, ['A10000001', '27/08/2026', '09:30', 'VFS Cairo', 'REF-1']]);

    const [first, second] = await Promise.all([
      ctx.dal.commitImport(admin(), file),
      ctx.dal.commitImport(admin(), file),
    ]);

    assert.equal(first.booked + second.booked, 1);

    const bookings = await ctx.collections.bookings();
    const charges = await ctx.collections.charges();
    assert.equal(await bookings.countDocuments({ undoneAt: null }), 1);
    assert.equal(await charges.countDocuments({ voidedAt: null }), 1);
  });

  it('re-uploading the same file afterwards changes nothing', async () => {
    await seedAdded(['A10000001']);
    const file = csvFile([HEADER, ['A10000001', '27/08/2026', '09:30', 'VFS Cairo', 'REF-1']]);

    await ctx.dal.commitImport(admin(), file);
    const again = await ctx.dal.commitImport(admin(), file);

    assert.ok(again.noop);
    assert.equal(again.booked, 0);

    const bookings = await ctx.collections.bookings();
    assert.equal(await bookings.countDocuments({}), 1);
  });

  it('never books a passport that was cancelled', async () => {
    const ids = await seedAdded(['A10000001']);
    await ctx.dal.changePassportStatus(admin(), ids[0]!, 'cancelled');

    await assert.rejects(
      () =>
        ctx.dal.commitImport(
          admin(),
          csvFile([HEADER, ['A10000001', '27/08/2026', '09:30', 'VFS Cairo', 'REF-1']]),
        ),
      (error: Error) => error.name === 'ValidationError',
    );
  });

  it('is admin-only', async () => {
    await seedAdded(['A10000001']);
    await assert.rejects(
      () =>
        ctx.dal.commitImport(asA(), csvFile([HEADER, ['A10000001', '27/08/2026', '09:30', 'VFS Cairo', 'REF-1']])),
      (error: Error) => error.name === 'ForbiddenError',
    );
  });
});

describe('undoing an import', () => {
  it('reverses the bookings, the statuses and the money together', async () => {
    const ids = await seedAdded(['A10000001', 'A10000002']);
    const committed = await ctx.dal.commitImport(
      admin(),
      csvFile([
        HEADER,
        ['A10000001', '27/08/2026', '09:30', 'VFS Cairo', 'REF-1'],
        ['A10000002', '27/08/2026', '10:00', 'VFS Cairo', 'REF-2'],
      ]),
    );

    const undone = await ctx.dal.undoImport(admin(), new ObjectId(committed.batchId));
    assert.equal(undone.bookingsUndone, 2);
    assert.equal(undone.chargesVoided, 2);
    assert.equal(undone.passportsReverted, 2);

    // Back where they were before the file arrived.
    for (const id of ids) {
      const passport = await ctx.dal.getPassport(admin(), id);
      assert.equal(passport.status, 'added');
    }

    // A rolled-back booking must not leave money owed.
    const charges = await ctx.collections.charges();
    assert.equal(await charges.countDocuments({ voidedAt: null }), 0);
    assert.equal(await charges.countDocuments({}), 2, 'the reversed charges stay as evidence');
  });

  it('frees the passport to be booked again by a later, correct file', async () => {
    await seedAdded(['A10000001']);
    const first = await ctx.dal.commitImport(
      admin(),
      csvFile([HEADER, ['A10000001', '20/08/2026', '09:30', 'VFS Cairo', 'WRONG']], 'wrong.csv'),
    );
    await ctx.dal.undoImport(admin(), new ObjectId(first.batchId));

    const second = await ctx.dal.commitImport(
      admin(),
      csvFile([HEADER, ['A10000001', '27/08/2026', '11:00', 'VFS Cairo', 'RIGHT']], 'right.csv'),
    );

    assert.equal(second.booked, 1);
    const bookings = await ctx.collections.bookings();
    const live = await bookings.find({ undoneAt: null }).toArray();
    assert.equal(live.length, 1);
    assert.equal(live[0]!.reference, 'RIGHT');
  });

  it('refuses to undo the same batch twice', async () => {
    await seedAdded(['A10000001']);
    const committed = await ctx.dal.commitImport(
      admin(),
      csvFile([HEADER, ['A10000001', '27/08/2026', '09:30', 'VFS Cairo', 'REF-1']]),
    );

    await ctx.dal.undoImport(admin(), new ObjectId(committed.batchId));
    await assert.rejects(
      () => ctx.dal.undoImport(admin(), new ObjectId(committed.batchId)),
      (error: Error) => error.name === 'ValidationError',
    );
  });

  it('writes both the import and the undo to the audit log', async () => {
    await seedAdded(['A10000001']);
    const committed = await ctx.dal.commitImport(
      admin(),
      csvFile([HEADER, ['A10000001', '27/08/2026', '09:30', 'VFS Cairo', 'REF-1']]),
    );
    await ctx.dal.undoImport(admin(), new ObjectId(committed.batchId));

    const audit = await ctx.collections.auditLog();
    assert.ok(await audit.findOne({ action: 'booking.import', entity: 'import_batch' }));
    assert.ok(await audit.findOne({ action: 'booking.import_undo' }));

    // And no passport number reached any of it.
    const entries = await audit.find({}).toArray();
    assert.equal(JSON.stringify(entries).includes('A10000001'), false);
  });

  it('is admin-only', async () => {
    await seedAdded(['A10000001']);
    const committed = await ctx.dal.commitImport(
      admin(),
      csvFile([HEADER, ['A10000001', '27/08/2026', '09:30', 'VFS Cairo', 'REF-1']]),
    );

    await assert.rejects(
      () => ctx.dal.undoImport(asA(), new ObjectId(committed.batchId)),
      (error: Error) => error.name === 'ForbiddenError',
    );
  });
});

describe('booked stays import-only', () => {
  it('cannot be reached by a manual change, a bulk change, or an agency', async () => {
    const ids = await seedAdded(['A10000001']);

    await assert.rejects(
      () => ctx.dal.changePassportStatus(admin(), ids[0]!, 'booked'),
      (error: Error) => error.name === 'ForbiddenError',
    );
    await assert.rejects(
      () => ctx.dal.changePassportStatuses(admin(), ids, 'booked'),
      (error: Error) => error.name === 'ForbiddenError',
    );
    await assert.rejects(
      () => ctx.dal.changePassportStatus(asA(), ids[0]!, 'booked'),
      (error: Error) => error.name === 'ForbiddenError',
    );
  });

  it('and once booked, an agency can no longer edit the passport', async () => {
    const ids = await seedAdded(['A10000001']);
    await ctx.dal.commitImport(
      admin(),
      csvFile([HEADER, ['A10000001', '27/08/2026', '09:30', 'VFS Cairo', 'REF-1']]),
    );

    await assert.rejects(
      () => ctx.dal.updatePassport(asA(), ids[0]!, { firstName: 'Changed' }),
      (error: Error) => error.name === 'ForbiddenError',
    );
  });
});
